{
  "hash": "d9917e8077a58edb926fef32d767cd89",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Longitudinal Mixed-Effects Modeling and Sensitivity Analyses in Simulated Parkinson’s Disease Data\"\nauthor: \"Dean Leonardi, Ph.D.\"\ndate: today\nparams:\n  missing_rate: 0.25\neditor: visual\n---\n\n## Abstract\n\nA longitudinal analysis for Parkinson’s patient UPDRS scores using MAR multiple imputation (MICE) sensitivity analysis and propensity score matching: a non-randomized, observational, simulated data study\n\n## Executive Summary\n\nThis report demonstrates a reproducible longitudinal clinical reporting workflow using R and Quarto in a simulated Parkinson’s disease observational study. Analyses include:\n\n- longitudinal mixed-effects modeling,\n- MAR multiple imputation sensitivity analysis (MICE),\n- propensity score matching,\n- treatment effect estimation,\n- and automated HTML reporting.\n\nThis workflow is intended as a methodological demonstration and does not represent a regulatory submission analysis.\n\n::: callout-note\n## Key Features Demonstrated\n\n- Longitudinal mixed-effects modeling\n- Sensitivity analysis workflows\n- Missing data handling\n- Propensity score matching\n- Automated statistical reporting\n- Interactive HTML reporting with Quarto\n- Reproducible research workflows\n- Clinical-style statistical interpretation\n:::\n\n## Background\n\nWe assessed the efficacy of treatment in patients with Parkinson’s disease (PD) using UPDRS (Unified Parkinson’s Disease Rating Scale) scores. In PD research, the UPDRS is the gold standard for measuring motor and non-motor symptoms.\n\n## Methods\n\nThis was a non-randomized, observational, 2-arm, simulated data study for adults with ages sampled from a normal distribution with mean 70 and standard deviation 12 years. Sex was sampled from a Bernoulli distribution with probability of being female 0.6. Treatment groups were assigned based on age and sex (non-random, simulating selection bias). We simulated longitudinal data for Parkinson’s patients with UPDRS scores measured at baseline, 1 year, and 2 years. The two groups were control and treatment. Longitudinal analysis was used to track changes in UPDRS scores across multiple time points to determine if treatment slows or accelerates disease progression and identifies symptom trajectories (e.g., motor decline, non-motor worsening) and supports trial design and stratification. The study data was simulated so that older and more females tended to get treatment. The primary endpoint was the differences between treatment groups (treatment - control) in UPDRS scores at year 2. No safety analysis was conducted. The ITT analysis set included all patients in the simulated data set. Multiple imputation by chained equations (MICE) under a missing-at-random (MAR) assumption, with M = 25 completed datasets pooled via Rubin's Rules, and propensity score matching to balance age and sex were utilized for sensitivity analyses.\n\n## Analysis\n\nWe simulate longitudinal data for Parkinson’s patients with UPDRS scores measured at baseline, 1 year, and 2 years. Two groups: Control and Treatment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(456)\n# Non-randomized observational study: older and more females tend to get treatment\nn_patients <- 400\npatients <- 1:n_patients\ntimes <- c(0, 1, 2)  # baseline, 1 year, 2 years\n\n# Non-random group assignment: function for treatment probability\nprob_treatment <- function(age, sex) {\n  plogis(-1 + 0.05*(age - 65) + 0.6*(sex == \"F\"))\n}\n\n# Create baseline covariates first\nbaseline_covariates <- data.frame(\n  Patient = as.factor(patients),\n  Age = rnorm(n_patients, mean = 70, sd = 12),  # Older population\n  Sex = sample(c(\"M\", \"F\"), n_patients, replace = TRUE, prob = c(0.4, 0.6))  # More females\n)\n\n# Assign groups based on age and sex (non-random, simulating selection bias)\nbaseline_covariates$Group <- as.factor(sapply(1:n_patients, function(i) {\n  if (runif(1) < prob_treatment(baseline_covariates$Age[i], baseline_covariates$Sex[i])) {\n    \"Treatment\"\n  } else {\n    \"Control\"\n  }\n}))\n\n# Create longitudinal data frame\ndata <- expand.grid(Patient = patients, Time = times)\ndata$Patient <- as.factor(data$Patient)\ndata$Time <- as.factor(data$Time)\n\n# Merge with baseline covariates\ndata <- data %>% left_join(baseline_covariates, by = \"Patient\")\n\n# Simulate UPDRS scores\ndata$UPDRS <- rnorm(nrow(data), mean = 35 + 5 * as.numeric(as.character(data$Time)) + \n                      ifelse(data$Group == \"Treatment\", -1.5, 0), sd = 6)\n\n# Parameterization of missing data\ndata$UPDRS <- ifelse(\n  runif(nrow(data)) < params$missing_rate &\n  data$Time != \"0\",\n  NA,\n  data$UPDRS\n)\n\ndata |>\n  head() |>\n  gt() |>\n  tab_header(title = \"Simulated Data — First Six Rows\") |>\n  tab_options(table.font.size = px(12))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mrmbfkslzr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mrmbfkslzr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mrmbfkslzr thead, #mrmbfkslzr tbody, #mrmbfkslzr tfoot, #mrmbfkslzr tr, #mrmbfkslzr td, #mrmbfkslzr th {\n  border-style: none;\n}\n\n#mrmbfkslzr p {\n  margin: 0;\n  padding: 0;\n}\n\n#mrmbfkslzr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mrmbfkslzr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mrmbfkslzr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mrmbfkslzr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mrmbfkslzr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mrmbfkslzr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mrmbfkslzr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mrmbfkslzr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mrmbfkslzr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mrmbfkslzr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mrmbfkslzr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mrmbfkslzr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mrmbfkslzr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mrmbfkslzr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mrmbfkslzr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrmbfkslzr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mrmbfkslzr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mrmbfkslzr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mrmbfkslzr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrmbfkslzr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mrmbfkslzr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrmbfkslzr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mrmbfkslzr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrmbfkslzr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mrmbfkslzr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrmbfkslzr .gt_left {\n  text-align: left;\n}\n\n#mrmbfkslzr .gt_center {\n  text-align: center;\n}\n\n#mrmbfkslzr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mrmbfkslzr .gt_font_normal {\n  font-weight: normal;\n}\n\n#mrmbfkslzr .gt_font_bold {\n  font-weight: bold;\n}\n\n#mrmbfkslzr .gt_font_italic {\n  font-style: italic;\n}\n\n#mrmbfkslzr .gt_super {\n  font-size: 65%;\n}\n\n#mrmbfkslzr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mrmbfkslzr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mrmbfkslzr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mrmbfkslzr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mrmbfkslzr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mrmbfkslzr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mrmbfkslzr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mrmbfkslzr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mrmbfkslzr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Simulated Data — First Six Rows</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Patient\">Patient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Age\">Age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sex\">Sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"UPDRS\">UPDRS</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">1</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">53.87774</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">M</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Control</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">37.56199</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">77.46131</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">M</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Treatment</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">42.38070</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">3</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">79.61050</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">F</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Control</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">44.47120</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">53.33329</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">F</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Treatment</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">34.82784</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">61.42772</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">F</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Treatment</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">32.51573</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_center\">6</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Age\" class=\"gt_row gt_right\">66.11127</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">F</td>\n<td headers=\"Group\" class=\"gt_row gt_center\">Control</td>\n<td headers=\"UPDRS\" class=\"gt_row gt_right\">34.24101</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# Add at the bottom of the simulate-data chunk\ndata_wide <- data |>\n  select(Patient, Time, Age, Sex, Group, UPDRS) |>\n  pivot_wider(\n    id_cols      = c(Patient, Age, Sex, Group),\n    names_from   = Time,\n    values_from  = UPDRS,\n    names_prefix = \"UPDRS_t\"\n  )\n```\n:::\n\n\n### Computational Reproducibility\n\nRandom seeds were pre-specified for all simulation and matching procedures to ensure reproducible analytical outputs.\n\n### Demographics\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ffywpfnmsq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ffywpfnmsq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ffywpfnmsq thead, #ffywpfnmsq tbody, #ffywpfnmsq tfoot, #ffywpfnmsq tr, #ffywpfnmsq td, #ffywpfnmsq th {\n  border-style: none;\n}\n\n#ffywpfnmsq p {\n  margin: 0;\n  padding: 0;\n}\n\n#ffywpfnmsq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ffywpfnmsq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ffywpfnmsq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ffywpfnmsq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ffywpfnmsq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ffywpfnmsq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ffywpfnmsq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ffywpfnmsq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ffywpfnmsq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ffywpfnmsq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ffywpfnmsq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ffywpfnmsq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ffywpfnmsq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ffywpfnmsq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ffywpfnmsq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffywpfnmsq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ffywpfnmsq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ffywpfnmsq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ffywpfnmsq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffywpfnmsq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ffywpfnmsq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffywpfnmsq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ffywpfnmsq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffywpfnmsq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ffywpfnmsq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffywpfnmsq .gt_left {\n  text-align: left;\n}\n\n#ffywpfnmsq .gt_center {\n  text-align: center;\n}\n\n#ffywpfnmsq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ffywpfnmsq .gt_font_normal {\n  font-weight: normal;\n}\n\n#ffywpfnmsq .gt_font_bold {\n  font-weight: bold;\n}\n\n#ffywpfnmsq .gt_font_italic {\n  font-style: italic;\n}\n\n#ffywpfnmsq .gt_super {\n  font-size: 65%;\n}\n\n#ffywpfnmsq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ffywpfnmsq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ffywpfnmsq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ffywpfnmsq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ffywpfnmsq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ffywpfnmsq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ffywpfnmsq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ffywpfnmsq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ffywpfnmsq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Table 1. Summary of Demographics and Baseline Characteristics</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNDAw\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 400</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipDb250cm9sKiogIApOID0gMjM0\"><span class='gt_from_md'><strong>Control</strong><br />\nN = 234</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipUcmVhdG1lbnQqKiAgCk4gPSAxNjY=\"><span class='gt_from_md'><strong>Treatment</strong><br />\nN = 166</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">70.71 (11.53)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">68.14 (10.87)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">74.34 (11.49)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    F</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">227 / 400 (57%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">124 / 234 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">103 / 166 (62%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    M</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">173 / 400 (43%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">110 / 234 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">63 / 166 (38%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">UPDRS</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">34.77 (5.85)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">35.59 (5.73)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">33.62 (5.84)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuIC8gTiAoJSk=\"><span class='gt_from_md'>Mean (SD); n / N (%)</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"KkRhdGEgaXMgc2ltdWxhdGVkKg==\"><span class='gt_from_md'><em>Data is simulated</em></span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Primary Analysis\n\nFit a linear mixed effects model to estimate least squares means differences between treatment groups at year 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$Group <- factor(data$Group,\n                     levels = c(\"Control\", \"Treatment\"))\nm1 <- lmer(UPDRS ~ Group*Time + Age + (1|Patient), data=data)\n\nsource(\"R/utils.R\")\n\n\nu4 <- extract_emm_table(m1)\nu4 |>\n  gt() |>\n  format_gt_table() |>\n  tab_header(\n    title = \"Table 2. Summary of Linear Mixed-Effects Model Predicting UPDRS by Treatment and Age at Year 2\"\n  ) |>\n  tab_footnote(\n    footnote = \"CI: 95% Confidence Interval; Formula: UPDRS ~ Group * Time + Age + (1 | Patient)\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vvvwqdkvmc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vvvwqdkvmc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vvvwqdkvmc thead, #vvvwqdkvmc tbody, #vvvwqdkvmc tfoot, #vvvwqdkvmc tr, #vvvwqdkvmc td, #vvvwqdkvmc th {\n  border-style: none;\n}\n\n#vvvwqdkvmc p {\n  margin: 0;\n  padding: 0;\n}\n\n#vvvwqdkvmc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vvvwqdkvmc .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vvvwqdkvmc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vvvwqdkvmc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vvvwqdkvmc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vvvwqdkvmc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vvvwqdkvmc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vvvwqdkvmc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vvvwqdkvmc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vvvwqdkvmc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vvvwqdkvmc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vvvwqdkvmc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vvvwqdkvmc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vvvwqdkvmc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vvvwqdkvmc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvvwqdkvmc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vvvwqdkvmc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vvvwqdkvmc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vvvwqdkvmc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvvwqdkvmc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vvvwqdkvmc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvvwqdkvmc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vvvwqdkvmc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvvwqdkvmc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vvvwqdkvmc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvvwqdkvmc .gt_left {\n  text-align: left;\n}\n\n#vvvwqdkvmc .gt_center {\n  text-align: center;\n}\n\n#vvvwqdkvmc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vvvwqdkvmc .gt_font_normal {\n  font-weight: normal;\n}\n\n#vvvwqdkvmc .gt_font_bold {\n  font-weight: bold;\n}\n\n#vvvwqdkvmc .gt_font_italic {\n  font-style: italic;\n}\n\n#vvvwqdkvmc .gt_super {\n  font-size: 65%;\n}\n\n#vvvwqdkvmc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vvvwqdkvmc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vvvwqdkvmc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vvvwqdkvmc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vvvwqdkvmc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vvvwqdkvmc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vvvwqdkvmc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vvvwqdkvmc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vvvwqdkvmc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Table 2. Summary of Linear Mixed-Effects Model Predicting UPDRS by Treatment and Age at Year 2</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI\">CI</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Control</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">46.294</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(45.401, 47.187)</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Treatment</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">43.287</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(42.276, 44.298)</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Treatment - Control</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-3.007</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-4.366, -1.648)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"> CI: 95% Confidence Interval; Formula: UPDRS ~ Group * Time + Age + (1 | Patient)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# emmeans estimates\nest_yr2 <- u4 |> filter(grepl(\"Treatment - Control\", Group)) |> pull(Estimate)\nci_yr2  <- u4 |> filter(grepl(\"Treatment - Control\", Group)) |> pull(CI)\n```\n:::\n\n\nThe longitudinal mixed-effects model demonstrated lower estimated UPDRS scores in the treatment group at Year 2 relative to control, consistent with simulated treatment benefit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics by treatment group and visit\nplot_data <- data %>%\n  group_by(Group, Time) %>%\n  summarize(\n    Mean = mean(UPDRS, na.rm = TRUE),\n    SD = sd(UPDRS, na.rm = TRUE),\n    N = sum(!is.na(UPDRS)),\n    SE = SD / sqrt(N),\n    Lower = Mean - 1.96 * SE,\n    Upper = Mean + 1.96 * SE,\n    .groups = \"drop\"\n  )\n\n# Convert Time to numeric for plotting\nplot_data$Time <- as.numeric(as.character(plot_data$Time))\n\n# Longitudinal profile plot\nggplot(plot_data,\n       aes(x = Time,\n           y = Mean,\n           color = Group,\n           group = Group)) +\n\n  geom_line(linewidth = 1.2) +\n\n  geom_point(size = 3) +\n\n  geom_errorbar(\n    aes(ymin = Lower, ymax = Upper),\n    width = 0.08,\n    linewidth = 0.7\n  ) +\n\n  scale_x_continuous(\n    breaks = c(0, 1, 2),\n    labels = c(\"Baseline\", \"Year 1\", \"Year 2\")\n  ) +\n\n  labs(\n    title = \"Longitudinal Mean UPDRS Profiles by Treatment Group\",\n    subtitle = \"Observed Mean Scores with 95% Confidence Intervals\",\n    x = \"Visit\",\n    y = \"Mean UPDRS Score\",\n    color = \"Treatment Group\"\n  ) +\n\n  theme_minimal(base_size = 13) +\n\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![Figure 1. Longitudinal mean UPDRS profiles by treatment group.](index_files/figure-html/longitudinal-profile-plot-1.png){width=1200}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  fitted(m1),\n  resid(m1),\n  xlab = \"Fitted Values\",\n  ylab = \"Residuals\",\n  main = \"Residuals vs Fitted\"\n)\n\nabline(h = 0, lty = 2)\n```\n\n::: {.cell-output-display}\n![Figure 2. Residual diagnostics for the primary mixed-effects model.](index_files/figure-html/residual-diagnostics-1.png){width=1050}\n:::\n:::\n\n\n## Findings\n\nFour hundred patients were assigned to receive control (n=234), or Treatment (n=166). Treatment reduced UPDRS score versus control (treatment 43.35 vs control 46.27; difference -3.01, 95% CI (-4.366, -1.648)).\n\n## Interpretation\n\nIn patients with Parkinson's disease, treatment reduced the UPDRS score at Year 2. These findings are based on simulated data and are intended as a methodological demonstration only.\n\n### Missing Data Analysis\n\nUnder a Missing At Random (MAR) assumption, missing UPDRS outcomes are predicted by observed covariates (Age, Sex, Group) and observed UPDRS values at other timepoints. Multiple imputation by chained equations (MICE) with predictive mean matching was used to generate M = 25 completed datasets. Fixed-effect estimates from each dataset were combined using Rubin's Rules to produce a single pooled estimate and standard error that properly accounts for within- and between-imputation uncertainty.\n\n#### Table 3a. Missingness Summary Prior to Imputation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oddtfktsbh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oddtfktsbh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oddtfktsbh thead, #oddtfktsbh tbody, #oddtfktsbh tfoot, #oddtfktsbh tr, #oddtfktsbh td, #oddtfktsbh th {\n  border-style: none;\n}\n\n#oddtfktsbh p {\n  margin: 0;\n  padding: 0;\n}\n\n#oddtfktsbh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oddtfktsbh .gt_title {\n  color: #333333;\n  font-size: 14px;\n  font-weight: bold;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oddtfktsbh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oddtfktsbh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oddtfktsbh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oddtfktsbh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oddtfktsbh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oddtfktsbh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oddtfktsbh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oddtfktsbh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oddtfktsbh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oddtfktsbh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oddtfktsbh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oddtfktsbh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oddtfktsbh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddtfktsbh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oddtfktsbh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oddtfktsbh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oddtfktsbh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddtfktsbh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oddtfktsbh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddtfktsbh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oddtfktsbh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddtfktsbh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oddtfktsbh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oddtfktsbh .gt_left {\n  text-align: left;\n}\n\n#oddtfktsbh .gt_center {\n  text-align: center;\n}\n\n#oddtfktsbh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oddtfktsbh .gt_font_normal {\n  font-weight: normal;\n}\n\n#oddtfktsbh .gt_font_bold {\n  font-weight: bold;\n}\n\n#oddtfktsbh .gt_font_italic {\n  font-style: italic;\n}\n\n#oddtfktsbh .gt_super {\n  font-size: 65%;\n}\n\n#oddtfktsbh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oddtfktsbh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oddtfktsbh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oddtfktsbh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oddtfktsbh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oddtfktsbh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oddtfktsbh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oddtfktsbh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oddtfktsbh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style>Table 3a. Missingness Summary Prior to Imputation</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>UPDRS_t0 (baseline) is fully observed by design</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N-patients\">N patients</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Missing-—-Year-1-(n)\">Missing — Year 1 (n)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Missing-—-Year-2-(n)\">Missing — Year 2 (n)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a%-Missing-—-Year-1\">% Missing — Year 1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a%-Missing-—-Year-2\">% Missing — Year 2</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"N patients\" class=\"gt_row gt_right\">400</td>\n<td headers=\"Missing — Year 1 (n)\" class=\"gt_row gt_right\">114</td>\n<td headers=\"Missing — Year 2 (n)\" class=\"gt_row gt_right\">86</td>\n<td headers=\"% Missing — Year 1\" class=\"gt_row gt_right\">28.5%</td>\n<td headers=\"% Missing — Year 2\" class=\"gt_row gt_right\">21.5%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n#### Figure 3a\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Figure 3a. Missing data pattern across patients and visits.](index_files/figure-html/missingness-pattern-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n::: {.cell cache.extra='[400,7]'}\n\n```{.r .cell-code}\n# ── 1. Prepare data for mice ──────────────────────────────────────────────────\n# Remove Patient ID before passing to mice (high-cardinality ID should not\n# be a predictor). Store IDs separately and re-attach after completion.\n\npatient_ids <- data_wide |> pull(Patient)\n\ndata_mice <- data_wide |>\n  select(-Patient) |>\n  mutate(\n    Sex   = factor(Sex,   levels = c(\"M\", \"F\")),\n    Group = factor(Group, levels = c(\"Control\", \"Treatment\"))\n  )\n\n# ── 2. Configure predictor matrix and imputation methods ──────────────────────\nini  <- mice(data_mice, maxit = 0, print = FALSE)\nmeth <- ini$method\npred <- ini$predictorMatrix\n\n# Baseline UPDRS is fully observed — exclude from imputation target\n# but retain as a predictor for Year 1 and Year 2 imputation\nmeth[\"UPDRS_t0\"] <- \"\"\npred[\"UPDRS_t0\", ] <- 0\n\n# pmm (predictive mean matching) is appropriate for bounded continuous scores:\n# it draws observed values close to the linear prediction, preserving the\n# empirical distribution and avoiding impossible out-of-range imputations\nmeth[c(\"UPDRS_t1\", \"UPDRS_t2\")] <- \"pmm\"\n\n# ── 3. Run mice ────────────────────────────────────────────────────────────────\nset.seed(2026)\nimp_mar <- mice(\n  data_mice,\n  m               = 25,    # 25 datasets: adequate for ~25% missingness\n  method          = meth,\n  predictorMatrix = pred,\n  maxit           = 15,    # iterations per dataset until convergence\n  print           = FALSE\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Trace plots: flat, well-mixed chains indicate convergence\nplot(imp_mar, c(\"UPDRS_t1\", \"UPDRS_t2\"), layout = c(2, 2))\n```\n\n::: {.cell-output-display}\n![Figure 3b. Convergence diagnostics for mice imputation. Mean and SD of imputed values should mix well (no trend) across iterations.](index_files/figure-html/mice-convergence-1.png){width=1200}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── 4. Fit LMER on each completed dataset ─────────────────────────────────────\n# For each of the M imputed wide datasets:\n#   (a) re-attach Patient IDs\n#   (b) reshape wide → long\n#   (c) fit the same LMER specification as the primary analysis\n\nfit_on_completed <- function(i) {\n  \n  wide_i <- mice::complete(imp_mar, action = i) |>\n    mutate(Patient = patient_ids)                  # restore patient ID\n  \n  long_i <- wide_i |>\n    pivot_longer(\n      cols         = starts_with(\"UPDRS_t\"),\n      names_to     = \"Time\",\n      names_prefix = \"UPDRS_t\",\n      values_to    = \"UPDRS\"\n    ) |>\n    mutate(\n      Time  = factor(Time,  levels = c(\"0\", \"1\", \"2\")),\n      Group = factor(Group, levels = c(\"Control\", \"Treatment\"))\n    )\n  \n  lmer(UPDRS ~ Group * Time + Age + (1 | Patient), data = long_i)\n}\n\nmodels_mar <- lapply(seq_len(imp_mar$m), fit_on_completed)\n\n# ── 5. Pool fixed effects via Rubin's Rules ───────────────────────────────────\n# mice::pool() uses broom.mixed::tidy() to extract estimates from each lmerMod\npooled_mar  <- mice::as.mira(models_mar) |> mice::pool()\npooled_summ <- summary(pooled_mar, conf.int = TRUE)\n\n# ── 6. Display pooled fixed effects table ─────────────────────────────────────\npooled_summ |>\n  as_tibble() |>\n  rename(\n    Parameter = term,\n    Estimate  = estimate,\n    SE        = std.error,\n    df        = df,\n    p         = p.value,\n    Lower     = `2.5 %`,\n    Upper     = `97.5 %`\n  ) |>\n  mutate(\n    across(c(Estimate, SE, Lower, Upper), \\(x) round(x, 3)),\n    CI = paste0(\"(\", round(Lower, 2), \", \", round(Upper, 2), \")\"),\n    p  = case_when(\n           p < 0.001 ~ \"< 0.001\",\n           TRUE      ~ as.character(round(p, 3))\n         )\n  ) |>\n  select(Parameter, Estimate, SE, CI, df, p) |>\n  gt() |>\n  tab_header(\n    title    = \"Table 3b. Pooled Fixed Effects — MAR Sensitivity Analysis\",\n    subtitle = \"MICE with Predictive Mean Matching; m = 25; Rubin's Rules\"\n  ) |>\n  cols_label(\n    Parameter = \"Parameter\",\n    Estimate  = \"Estimate\",\n    SE        = \"Std. Error\",\n    CI        = \"95% CI\",\n    df        = \"Pooled df\",\n    p         = \"p-value\"\n  ) |>\n  tab_style(\n    style     = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_footnote(\n    footnote = \"Pooled using Rubin's Rules. Formula: UPDRS ~ Group × Time + Age + (1 | Patient). FMI reported in Table 3c.\"\n  ) |>\n  tab_options(\n    table.font.size           = px(13),\n    heading.title.font.size   = px(14),\n    heading.title.font.weight = \"bold\",\n    table.width               = pct(100)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"clcurzjodw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#clcurzjodw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#clcurzjodw thead, #clcurzjodw tbody, #clcurzjodw tfoot, #clcurzjodw tr, #clcurzjodw td, #clcurzjodw th {\n  border-style: none;\n}\n\n#clcurzjodw p {\n  margin: 0;\n  padding: 0;\n}\n\n#clcurzjodw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#clcurzjodw .gt_title {\n  color: #333333;\n  font-size: 14px;\n  font-weight: bold;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#clcurzjodw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#clcurzjodw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#clcurzjodw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#clcurzjodw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#clcurzjodw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#clcurzjodw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#clcurzjodw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#clcurzjodw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#clcurzjodw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#clcurzjodw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#clcurzjodw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#clcurzjodw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#clcurzjodw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clcurzjodw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#clcurzjodw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#clcurzjodw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#clcurzjodw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clcurzjodw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#clcurzjodw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clcurzjodw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#clcurzjodw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clcurzjodw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#clcurzjodw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clcurzjodw .gt_left {\n  text-align: left;\n}\n\n#clcurzjodw .gt_center {\n  text-align: center;\n}\n\n#clcurzjodw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#clcurzjodw .gt_font_normal {\n  font-weight: normal;\n}\n\n#clcurzjodw .gt_font_bold {\n  font-weight: bold;\n}\n\n#clcurzjodw .gt_font_italic {\n  font-style: italic;\n}\n\n#clcurzjodw .gt_super {\n  font-size: 65%;\n}\n\n#clcurzjodw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#clcurzjodw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#clcurzjodw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#clcurzjodw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#clcurzjodw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#clcurzjodw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#clcurzjodw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#clcurzjodw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#clcurzjodw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Table 3b. Pooled Fixed Effects — MAR Sensitivity Analysis</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>MICE with Predictive Mean Matching; m = 25; Rubin's Rules</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SE\">Std. Error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"df\">Pooled df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"p\">p-value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">(Intercept)</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">36.377</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">1.291</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(33.84, 38.92)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">321.7212</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt; 0.001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">GroupTreatment</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-1.903</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.621</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-3.12, -0.69)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1176.0182</td>\n<td headers=\"p\" class=\"gt_row gt_left\">0.002</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">Time1</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">3.520</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.605</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(2.33, 4.71)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">493.0135</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt; 0.001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">Time2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">10.671</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.601</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(9.49, 11.85)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">539.5810</td>\n<td headers=\"p\" class=\"gt_row gt_left\">&lt; 0.001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">Age</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-0.012</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.018</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-0.05, 0.02)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">279.5735</td>\n<td headers=\"p\" class=\"gt_row gt_left\">0.524</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">GroupTreatment:Time1</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">2.892</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.958</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(1.01, 4.78)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">394.5858</td>\n<td headers=\"p\" class=\"gt_row gt_left\">0.003</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_center\">GroupTreatment:Time2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-0.998</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.921</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-2.81, 0.81)</td>\n<td headers=\"df\" class=\"gt_row gt_right\">627.1268</td>\n<td headers=\"p\" class=\"gt_row gt_left\">0.279</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"> Pooled using Rubin's Rules. Formula: UPDRS ~ Group × Time + Age + (1 | Patient). FMI reported in Table 3c.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── 7. Pooled treatment effect at Year 2 formatted like primary analysis ──────\n# emmeans is computed for each imputed model, then estimates and SEs are\n# combined using Rubin's Rules. The Satterthwaite df from emmeans is used\n# in the Barnard-Rubin (1999) degrees-of-freedom approximation.\n\npool_emmeans_contrast <- function(models, time_level = \"2\") {\n  \n  # Extract Treatment - Control contrast at the requested timepoint\n  extract_one <- function(mod) {\n    em  <- emmeans(mod, ~ Group | Time)\n    ct  <- contrast(em, method = \"trt.vs.ctrl\", ref = \"Control\")\n    row <- as.data.frame(ct) |> filter(Time == time_level)\n    list(\n      est = row$estimate,\n      se  = row$SE,\n      df  = row$df      # Satterthwaite df\n    )\n  }\n  \n  res   <- lapply(models, extract_one)\n  M     <- length(res)\n  ests  <- sapply(res, `[[`, \"est\")\n  ses   <- sapply(res, `[[`, \"se\")\n  dfs   <- sapply(res, `[[`, \"df\")\n  \n  # Rubin's Rules\n  Q_bar <- mean(ests)                          # pooled estimate\n  U_bar <- mean(ses^2)                         # average within-imputation variance\n  B     <- var(ests)                           # between-imputation variance\n  T_var <- U_bar + (1 + 1 / M) * B            # total variance\n  SE_p  <- sqrt(T_var)\n  \n  # Fraction of missing information (FMI)\n  r   <- (1 + 1 / M) * B / U_bar\n  fmi <- r / (1 + r)\n  \n  # Barnard-Rubin (1999) pooled degrees of freedom\n  df_old <- mean(dfs)\n  df_m   <- (M - 1) / r^2\n  df_obs <- (df_old + 1) / (df_old + 3) * df_old * (1 - r)\n  df_p   <- 1 / (1 / df_m + 1 / df_obs)\n  \n  ci <- Q_bar + qt(c(0.025, 0.975), df = df_p) * SE_p\n  \n  tibble(\n    Contrast    = \"Treatment \\u2212 Control\",\n    Time        = paste0(\"Year \", time_level),\n    Estimate    = round(Q_bar, 3),\n    SE          = round(SE_p,  3),\n    CI          = paste0(\"(\", round(ci[1], 2), \", \", round(ci[2], 2), \")\"),\n    FMI         = round(fmi, 3)\n  )\n}\n\ncontrast_pooled <- pool_emmeans_contrast(models_mar, time_level = \"2\")\n\ncontrast_pooled |>\n  gt() |>\n  tab_header(\n    title    = \"Table 3c. Pooled Treatment Effect at Year 2 — MAR Sensitivity Analysis\",\n    subtitle = \"MICE / Predictive Mean Matching; m = 25; Rubin's Rules\"\n  ) |>\n  cols_label(\n    Contrast = \"Contrast\",\n    Time     = \"Timepoint\",\n    Estimate = \"Estimate\",\n    SE       = \"Std. Error\",\n    CI       = \"95% CI\",\n    FMI      = \"FMI\"\n  ) |>\n  tab_style(\n    style     = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |>\n  tab_footnote(\n    footnote = paste0(\n      \"FMI: Fraction of Missing Information \\u2014 proportion of total variance \",\n      \"attributable to missing data. Higher values indicate stronger sensitivity \",\n      \"to the MAR assumption. df computed via Barnard-Rubin (1999) approximation.\"\n    )\n  ) |>\n  tab_options(\n    table.font.size           = px(13),\n    heading.title.font.size   = px(14),\n    heading.title.font.weight = \"bold\",\n    table.width               = pct(100)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uxreuyvmyx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uxreuyvmyx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uxreuyvmyx thead, #uxreuyvmyx tbody, #uxreuyvmyx tfoot, #uxreuyvmyx tr, #uxreuyvmyx td, #uxreuyvmyx th {\n  border-style: none;\n}\n\n#uxreuyvmyx p {\n  margin: 0;\n  padding: 0;\n}\n\n#uxreuyvmyx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uxreuyvmyx .gt_title {\n  color: #333333;\n  font-size: 14px;\n  font-weight: bold;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uxreuyvmyx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uxreuyvmyx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uxreuyvmyx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uxreuyvmyx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uxreuyvmyx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uxreuyvmyx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uxreuyvmyx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uxreuyvmyx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uxreuyvmyx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uxreuyvmyx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uxreuyvmyx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uxreuyvmyx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uxreuyvmyx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxreuyvmyx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uxreuyvmyx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uxreuyvmyx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uxreuyvmyx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxreuyvmyx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uxreuyvmyx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxreuyvmyx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uxreuyvmyx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxreuyvmyx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uxreuyvmyx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxreuyvmyx .gt_left {\n  text-align: left;\n}\n\n#uxreuyvmyx .gt_center {\n  text-align: center;\n}\n\n#uxreuyvmyx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uxreuyvmyx .gt_font_normal {\n  font-weight: normal;\n}\n\n#uxreuyvmyx .gt_font_bold {\n  font-weight: bold;\n}\n\n#uxreuyvmyx .gt_font_italic {\n  font-style: italic;\n}\n\n#uxreuyvmyx .gt_super {\n  font-size: 65%;\n}\n\n#uxreuyvmyx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uxreuyvmyx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uxreuyvmyx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uxreuyvmyx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uxreuyvmyx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uxreuyvmyx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uxreuyvmyx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uxreuyvmyx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uxreuyvmyx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Table 3c. Pooled Treatment Effect at Year 2 — MAR Sensitivity Analysis</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>MICE / Predictive Mean Matching; m = 25; Rubin's Rules</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Contrast\">Contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Time\">Timepoint</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"SE\">Std. Error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"FMI\">FMI</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Contrast\" class=\"gt_row gt_left\">Treatment − Control</td>\n<td headers=\"Time\" class=\"gt_row gt_left\">Year 2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-2.901</td>\n<td headers=\"SE\" class=\"gt_row gt_right\">0.701</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-4.28, -1.52)</td>\n<td headers=\"FMI\" class=\"gt_row gt_right\">0.222</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"> FMI: Fraction of Missing Information — proportion of total variance attributable to missing data. Higher values indicate stronger sensitivity to the MAR assumption. df computed via Barnard-Rubin (1999) approximation.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nResults from the MAR multiple imputation sensitivity analysis are presented in Tables 3b and 3c. Consistency with the primary analysis estimates would support robustness of the primary findings to the missing-at-random assumption. The Fraction of Missing Information (FMI) quantifies the proportion of uncertainty attributable to missing data; values below 0.10 are generally considered low.\n\n### Propensity Score Matching\n\nAssuming the groups are not randomized, use propensity score matching to balance covariates of age and sex. Based on the matched data, fit the longitudinal mixed-effects model and estimate least squares means differences between treatment groups at year 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\n# Propensity score matching and evaluation\nvars <- c(\"Age\", \"Sex\")\ntable_before <- CreateTableOne(vars = vars,\n                               strata = \"Group\",\n                               data = baseline_covariates,\n                               test = FALSE)\n\n#print(table_before, smd = TRUE)\n\nprint(table_before, smd = TRUE, printToggle = FALSE) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Characteristic\") |>\n  gt() |>\n  format_gt_table() |>           # your existing utility\n  tab_header(title = \"Table 4. Balance Before Matching\") |>\n  tab_footnote(\"SMD < 0.10 indicates acceptable balance.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yafmoldpel\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yafmoldpel table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yafmoldpel thead, #yafmoldpel tbody, #yafmoldpel tfoot, #yafmoldpel tr, #yafmoldpel td, #yafmoldpel th {\n  border-style: none;\n}\n\n#yafmoldpel p {\n  margin: 0;\n  padding: 0;\n}\n\n#yafmoldpel .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yafmoldpel .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yafmoldpel .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yafmoldpel .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yafmoldpel .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yafmoldpel .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yafmoldpel .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yafmoldpel .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yafmoldpel .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yafmoldpel .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yafmoldpel .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yafmoldpel .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yafmoldpel .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yafmoldpel .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yafmoldpel .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yafmoldpel .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yafmoldpel .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yafmoldpel .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yafmoldpel .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yafmoldpel .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yafmoldpel .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yafmoldpel .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yafmoldpel .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yafmoldpel .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yafmoldpel .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yafmoldpel .gt_left {\n  text-align: left;\n}\n\n#yafmoldpel .gt_center {\n  text-align: center;\n}\n\n#yafmoldpel .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yafmoldpel .gt_font_normal {\n  font-weight: normal;\n}\n\n#yafmoldpel .gt_font_bold {\n  font-weight: bold;\n}\n\n#yafmoldpel .gt_font_italic {\n  font-style: italic;\n}\n\n#yafmoldpel .gt_super {\n  font-size: 65%;\n}\n\n#yafmoldpel .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yafmoldpel .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yafmoldpel .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yafmoldpel .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yafmoldpel .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yafmoldpel .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yafmoldpel .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yafmoldpel .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yafmoldpel div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Table 4. Balance Before Matching</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Characteristic\">Characteristic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SMD\">SMD</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">n</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">  234</td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">  166</td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"></td></tr>\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">Age (mean (SD))</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">68.14 (10.87)</td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">74.34 (11.49)</td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"> 0.554</td></tr>\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">Sex = M (%)</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">  110 (47.0) </td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">   63 (38.0) </td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"> 0.184</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"> SMD &lt; 0.10 indicates acceptable balance.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nmatch_model2 <- matchit(Group ~ Age + Sex,\n                        data = baseline_covariates,\n                        method = \"nearest\",\n                        link=\"logit\",\n                        distance=\"glm\")\n\nmatched_data2 <- match.data(match_model2)\n#table(matched_data2$Group)\n\n\ntable_after <- CreateTableOne(vars = vars,\n                              strata = \"Group\",\n                              data = matched_data2,\n                              test = FALSE)\n\n#print(table_after, smd = TRUE)\n\nprint(table_after, smd = TRUE, printToggle = FALSE) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Characteristic\") |>\n  gt() |>\n  format_gt_table() |>           # your existing utility\n  tab_header(title = \"Table 5. Balance After Matching\") |>\n  tab_footnote(\"SMD < 0.10 indicates acceptable balance.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zbxsonqljv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zbxsonqljv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zbxsonqljv thead, #zbxsonqljv tbody, #zbxsonqljv tfoot, #zbxsonqljv tr, #zbxsonqljv td, #zbxsonqljv th {\n  border-style: none;\n}\n\n#zbxsonqljv p {\n  margin: 0;\n  padding: 0;\n}\n\n#zbxsonqljv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zbxsonqljv .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zbxsonqljv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zbxsonqljv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zbxsonqljv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zbxsonqljv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zbxsonqljv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zbxsonqljv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zbxsonqljv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zbxsonqljv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zbxsonqljv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zbxsonqljv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zbxsonqljv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zbxsonqljv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zbxsonqljv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbxsonqljv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zbxsonqljv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zbxsonqljv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zbxsonqljv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbxsonqljv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zbxsonqljv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbxsonqljv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zbxsonqljv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbxsonqljv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zbxsonqljv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbxsonqljv .gt_left {\n  text-align: left;\n}\n\n#zbxsonqljv .gt_center {\n  text-align: center;\n}\n\n#zbxsonqljv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zbxsonqljv .gt_font_normal {\n  font-weight: normal;\n}\n\n#zbxsonqljv .gt_font_bold {\n  font-weight: bold;\n}\n\n#zbxsonqljv .gt_font_italic {\n  font-style: italic;\n}\n\n#zbxsonqljv .gt_super {\n  font-size: 65%;\n}\n\n#zbxsonqljv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zbxsonqljv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zbxsonqljv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zbxsonqljv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zbxsonqljv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zbxsonqljv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zbxsonqljv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zbxsonqljv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zbxsonqljv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Table 5. Balance After Matching</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Characteristic\">Characteristic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SMD\">SMD</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">n</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">  166</td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">  166</td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"></td></tr>\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">Age (mean (SD))</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">72.12 (9.90)</td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">74.34 (11.49)</td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"> 0.207</td></tr>\n    <tr><td headers=\"Characteristic\" class=\"gt_row gt_left\">Sex = M (%)</td>\n<td headers=\"Control\" class=\"gt_row gt_right\">   67 (40.4) </td>\n<td headers=\"Treatment\" class=\"gt_row gt_right\">   63 (38.0) </td>\n<td headers=\"SMD\" class=\"gt_row gt_right\"> 0.049</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"> SMD &lt; 0.10 indicates acceptable balance.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# Subset orginal data based on patients identified by Propensity score matching\nmatched_pid <- matched_data2 |> select(Patient)\nmatched_data_final <- left_join(matched_pid, data, by = \"Patient\")\n\n\n# Generate linear mixed effects model on matched population\nmatched_data_final$Group <- factor(\n    matched_data_final$Group, \n    levels = c(\"Control\", \"Treatment\"))\n\nm3 <- lmer(UPDRS ~ Group*Time + Age + (1|Patient), data=matched_data_final)\n\nw4 <- extract_emm_table(m3)\nw4 |>\n  gt() |>\n  format_gt_table() |>\n  tab_header(\n    title = \"Table 6. Summary of Linear Mixed-Effects Model Predicting UPDRS by Treatment and Age at Year 2\",\n    subtitle = \"Propensity Score Matching\"\n  ) |>\n  tab_footnote(\n    footnote = \"CI: 95% Confidence Interval; Formula: UPDRS ~ Group * Time + Age + (1 | Patient)\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rbelxepclc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rbelxepclc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rbelxepclc thead, #rbelxepclc tbody, #rbelxepclc tfoot, #rbelxepclc tr, #rbelxepclc td, #rbelxepclc th {\n  border-style: none;\n}\n\n#rbelxepclc p {\n  margin: 0;\n  padding: 0;\n}\n\n#rbelxepclc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rbelxepclc .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rbelxepclc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rbelxepclc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rbelxepclc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rbelxepclc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rbelxepclc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rbelxepclc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rbelxepclc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rbelxepclc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rbelxepclc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rbelxepclc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rbelxepclc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rbelxepclc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rbelxepclc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rbelxepclc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rbelxepclc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rbelxepclc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rbelxepclc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rbelxepclc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rbelxepclc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rbelxepclc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rbelxepclc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rbelxepclc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rbelxepclc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rbelxepclc .gt_left {\n  text-align: left;\n}\n\n#rbelxepclc .gt_center {\n  text-align: center;\n}\n\n#rbelxepclc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rbelxepclc .gt_font_normal {\n  font-weight: normal;\n}\n\n#rbelxepclc .gt_font_bold {\n  font-weight: bold;\n}\n\n#rbelxepclc .gt_font_italic {\n  font-style: italic;\n}\n\n#rbelxepclc .gt_super {\n  font-size: 65%;\n}\n\n#rbelxepclc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rbelxepclc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rbelxepclc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rbelxepclc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rbelxepclc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rbelxepclc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rbelxepclc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rbelxepclc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rbelxepclc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Table 6. Summary of Linear Mixed-Effects Model Predicting UPDRS by Treatment and Age at Year 2</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Propensity Score Matching</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Time\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI\">CI</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Control</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">45.922</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(44.848, 46.996)</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Treatment</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">43.275</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(42.268, 44.281)</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_center\">Treatment - Control</td>\n<td headers=\"Time\" class=\"gt_row gt_center\">2</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-2.647</td>\n<td headers=\"CI\" class=\"gt_row gt_right\">(-4.121, -1.174)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"> CI: 95% Confidence Interval; Formula: UPDRS ~ Group * Time + Age + (1 | Patient)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nPropensity score matching improved baseline covariate balance between treatment groups while preserving estimated treatment differences at Year 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Love Plot\nlove.plot(\n  match_model2,\n  binary = \"std\",\n  thresholds = c(m = 0.1),\n  abs = TRUE,\n  var.order = \"unadjusted\",\n  stars = \"raw\"\n)\n```\n\n::: {.cell-output-display}\n![Figure 4. Covariate balance before and after propensity score matching.](index_files/figure-html/covbal-plot-1.png){width=1200}\n:::\n:::\n\n\n## Conclusions\n\nThis report demonstrates a reproducible and automated longitudinal clinical reporting workflow using modern R and Quarto methodologies. The analysis integrates mixed-effects modeling, missing data sensitivity analyses, and propensity score matching within a publication-style HTML reporting framework suitable for exploratory clinical and real-world evidence applications.\n\nThe workflow illustrates approaches commonly used in pharmaceutical and biotechnology clinical development environments for statistical analysis, reproducibility, and reporting automation.\n\n## Limitations\n\nThis report uses simulated observational data for methodological demonstration purposes. Results should not be interpreted clinically. Missing data sensitivity analyses use MICE with predictive mean matching under a missing-at-random (MAR) assumption. Whether the MAR assumption holds cannot be verified from the observed data alone; MNAR sensitivity analyses (e.g., reference-based methods using the rbmi package) would be required for regulatory-grade submissions.\n\n## Reproducibility\n\nThis report was generated using a reproducible Quarto workflow in R.\\\nAll analyses, figures, tables, and statistical outputs were generated programmatically from simulated source data.\n\nKey components include:\n\n- automated data simulation,\n- longitudinal mixed-effects modeling,\n- MAR multiple imputation using MICE (m = 25, Rubin's Rules),\n- propensity score matching,\n- reproducible statistical reporting,\n- and parameterized report generation.\n\nThe workflow is designed to reflect modern clinical reporting and real-world evidence analysis practices used in pharmaceutical and biotechnology settings.\n\n## Appendix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.0 (2026-04-24 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/Los_Angeles\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices datasets  utils     methods   base     \n\nother attached packages:\n [1] naniar_1.1.0        broom.mixed_0.2.9.7 mice_3.19.0        \n [4] cobalt_4.6.2        MatchIt_4.7.2       tableone_0.13.2    \n [7] emmeans_2.0.3       lmerTest_3.2-1      lme4_2.0-1         \n[10] Matrix_1.7-5        gt_1.3.0            gtsummary_2.5.0    \n[13] lubridate_1.9.5     forcats_1.0.1       stringr_1.6.0      \n[16] dplyr_1.2.1         purrr_1.2.2         readr_2.2.0        \n[19] tidyr_1.3.2         tibble_3.3.1        ggplot2_4.0.3      \n[22] tidyverse_2.0.0    \n\nloaded via a namespace (and not attached):\n [1] Rdpack_2.6.6        DBI_1.3.0           rlang_1.2.0        \n [4] magrittr_2.0.5      furrr_0.4.0         otel_0.2.0         \n [7] e1071_1.7-17        compiler_4.6.0      vctrs_0.7.3        \n[10] pkgconfig_2.0.3     shape_1.4.6.1       fastmap_1.2.0      \n[13] backports_1.5.1     labeling_0.4.3      rmarkdown_2.31     \n[16] markdown_2.0        tzdb_0.5.0          haven_2.5.5        \n[19] nloptr_2.2.1        visdat_0.6.0        xfun_0.57          \n[22] glmnet_5.0          jomo_2.7-6          labelled_2.16.0    \n[25] litedown_0.9        jsonlite_2.0.0      chk_0.10.0         \n[28] pan_1.9             broom_1.0.13        parallel_4.6.0     \n[31] R6_2.6.1            stringi_1.8.7       RColorBrewer_1.1-3 \n[34] parallelly_1.47.0   boot_1.3-32         rpart_4.1.27       \n[37] numDeriv_2016.8-1.1 estimability_1.5.1  Rcpp_1.1.1-1.1     \n[40] iterators_1.0.14    knitr_1.51          zoo_1.8-15         \n[43] base64enc_0.1-6     splines_4.6.0       nnet_7.3-20        \n[46] timechange_0.4.0    tidyselect_1.2.1    rstudioapi_0.18.0  \n[49] yaml_2.3.12         codetools_0.2-20    listenv_0.10.1     \n[52] lattice_0.22-9      withr_3.0.2         S7_0.2.2           \n[55] coda_0.19-4.1       evaluate_1.0.5      future_1.70.0      \n[58] survival_3.8-6      proxy_0.4-29        survey_4.5         \n[61] xml2_1.5.2          pillar_1.11.1       renv_1.2.3         \n[64] foreach_1.5.2       stats4_4.6.0        reformulas_0.4.4   \n[67] generics_0.1.4      hms_1.1.4           commonmark_2.0.0   \n[70] scales_1.4.0        minqa_1.2.8         globals_0.19.1     \n[73] xtable_1.8-8        class_7.3-23        glue_1.8.1         \n[76] tools_4.6.0         fs_2.1.0            mvtnorm_1.3-7      \n[79] grid_4.6.0          mitools_2.4         rbibutils_2.4.1    \n[82] cards_0.7.1         nlme_3.1-169        cli_3.6.6          \n[85] gtable_0.3.6        sass_0.4.10         digest_0.6.39      \n[88] htmlwidgets_1.6.4   farver_2.1.2        htmltools_0.5.9    \n[91] lifecycle_1.0.5     mitml_0.4-5         MASS_7.3-65        \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}